default[:tomcat][:home] = "/opt/tomcat"
default[:tomcat][:version] = "6.0.35"
default[:tomcat][:catalina_home] = "/opt/tomcat/apache-tomcat-#{default[:tomcat][:version]}"
default[:tomcat][:instances_base] = "/opt/tomcat/instances"
default[:tomcat][:log_dir] = "/var/log/tomcat"
default[:tomcat][:user] = "tomcat"
default[:tomcat][:warp_file] = "apache-tomcat-#{default[:tomcat][:version]}_`lsb_release -cs`_`arch`.warp"
