source :rubygems

gem 'rake', '0.8.7'
gem 'i18n', '0.4.2'
gem 'rails', '2.3.14'
gem 'rack', '1.1.1'
gem 'rubytree'
gem 'coderay', '~>0.9.7'
gem 'aasm'
gem 'block_helpers'
gem 'net-ldap'

group :development do
  gem 'capistrano'
  gem 'sqlite3'
end

group :production do
  gem 'mysql'
  gem 'execjs'
  gem 'unicorn'
  gem 'therubyracer'
  gem 'mysql'
end
